[build]
  command = "npx @11ty/eleventy"
  publish = "dist"
  functions = "src/_functions"
  
[[redirects]]
  from = "/widget/*"
  to = "/.netlify/functions/widget"
  status = 200
  
  [[plugins]]
  package = "@netlify/plugin-sitemap"
  
    [plugins.inputs]
    buildDir = "dist"
    prettyURLs = true
    trailingSlash = true